url: 'https://griffinmoore.com'
baseurl: 'griffinmoore.github.io'
title: 'Griffin Moore'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
